using System.Collections.Generic;
using System.Drawing;

namespace ZeldaMessage
{
    public static class DataMajora
    {
        public enum MsgControlCode
        {
            COLOR_DEFAULT = 0x00,
            COLOR_RED = 0x01,
            COLOR_GREEN = 0x02,
            COLOR_BLUE = 0x03,
            COLOR_YELLOW = 0x04,
            COLOR_NAVY = 0x05,
            COLOR_PINK = 0x06,
            COLOR_SILVER = 0x07,
            COLOR_ORANGE = 0x08,
            UNK_09 = 0x09,
            SLOW_TEXT = 0x0A,
            SWAMP_CRUISE_HITS = 0x0B,
            STRAY_FAIRY_SCORE = 0x0C,
            GOLD_SKULLTULAS = 0x0D,
            FISH_WEIGHT = 0xE,
            UNK_0F = 0xF,
            NEW_BOX = 0x10,
            LINE_BREAK = 0x11,
            NEW_BOX_INCOMPL = 0x12,
            RESET_CURSOR = 0x13,
            SHIFT = 0x14,
            NOSKIP = 0x15,
            PLAYER = 0x16,
            DI = 0x17,
            DC = 0x18,
            NOSKIP_SOUND = 0x19,
            PERSISTENT = 0x1A,
            DELAY_DI = 0x1B,
            FADE = 0x1C,
            DELAY_END = 0x1D,
            SOUND = 0x1E,
            DELAY_DC = 0x1F,
            END = 0xBF,
            BACKGROUND = 0xC1,
            TWO_CHOICES = 0xC2,
            THREE_CHOICES = 0xC3,
            POSTMAN_RESULTS = 0xC4,
            TIMER = 0xC5,
            TIMER2 = 0xC6,
            MOON_CRASH_TIME = 0xC7,
            DEKU_RESULTS = 0xC8,
            TIMER3 = 0xC9,
            TIMER4 = 0xCA,
            SHOOTING_GALLERY_RESULT = 0xCB,
            BANK_PROMPT = 0xCC,
            RUPEES_ENTERED = 0xCD,
            RUPEES_IN_BANK = 0xCE,
            TIME_REMAINING = 0xCF,
            BET_RUPEES = 0xD0,
            PROMPT_BOMBER_CODE = 0xD1,
            ITEM_PROMPT = 0xD2,
            UNK_D3 = 0xD3,
            SOARING_DESTINATION = 0xD4,
            PROMPT_LOTTERY_NUMBER = 0xD5,
            OCEANSIDE_HOUSE_ORDER = 0xD6,
            WOODFALL_FAIRIES_REMAIN = 0xD7,
            SNOWHEAD_FAIRIES_REMAIN = 0xD8,
            BAY_FAIRIES_REMAIN = 0xD9,
            IKANA_FAIRIES_REMAIN = 0xDA,
            SWAMP_CRUISE_RESULT = 0xDB,
            WINNING_LOTTERY_NUM = 0xDC,
            PLAYER_LOTTERY_NUM = 0xDD,
            ITEM_VALUE = 0xDE,
            BOMBER_CODE = 0xDF,
            END_CONVERSATION = 0xE0,
            OCEANSIDE_HOUSE_ORDER_1 = 0xE1,
            OCEANSIDE_HOUSE_ORDER_2 = 0xE2,
            OCEANSIDE_HOUSE_ORDER_3 = 0xE3,
            OCEANSIDE_HOUSE_ORDER_4 = 0xE4,
            OCEANSIDE_HOUSE_ORDER_5 = 0xE5,
            OCEANSIDE_HOUSE_ORDER_6 = 0xE6,
            MOON_CRASH_HOURS_REMAIN = 0xE7,
            UNTIL_MORNING = 0xE8,
            UNK_E9 = 0xE9,
            UNK_EA = 0xEA,
            UNK_EB = 0xEB,
            UNK_EC = 0xEC,
            UNK_ED = 0xED,
            UNK_EE = 0xEE,
            UNK_EF = 0xEF,
            TOTAL_IN_BANK = 0xF0,
            UNK_F1 = 0xF1,
            UNK_F2 = 0xF2,
            UNK_F3 = 0xF3,
            UNK_F4 = 0xF4,
            UNK_F5 = 0xF5,
            TOWN_SHOOTING_HIGHSCORE = 0xF6,
            UNK_F7 = 0xF7,
            UNK_F8 = 0xF8,
            EPONA_ARCHERY_HIGHSCORE = 0xF9,
            DEKU_HIGHSCORE_DAY1 = 0xFA,
            DEKU_HIGHSCORE_DAY2 = 0xFB,
            DEKU_HIGHSCORE_DAY3 = 0xFC,
            UNK_FD = 0xFD,
            UNK_FE = 0xFE,
            UNK_FF = 0xFF,


            DASH = 0x7F,
            À = 0x80,
            Á = 0x81,
            Â = 0x82,
            Ä = 0x83,
            Ç = 0x84,
            È = 0x85,
            É = 0x86,
            Ê = 0x87,
            Ë = 0x88,
            Ì = 0x89,
            Í = 0x8A,
            Î = 0x8B,
            Ï = 0x8C,
            Ñ = 0x8D,
            Ò = 0x8E,
            Ó = 0x8F,
            Ô = 0x90,
            Ö = 0x91,
            Ù = 0x92,
            Ú = 0x93,
            Û = 0x94,
            Ü = 0x95,
            ß = 0x96,
            à = 0x97,
            á = 0x98,
            â = 0x99,
            ä = 0x9A,
            ç = 0x9B,
            è = 0x9C,
            é = 0x9D,
            ê = 0x9E,
            ë = 0x9F,
            ì = 0xA0,
            í = 0xA1,
            î = 0xA2,
            ï = 0xA3,
            ñ = 0xA4,
            ò = 0xA5,
            ó = 0xA6,
            ô = 0xA7,
            ö = 0xA8,
            ù = 0xA9,
            ú = 0xAA,
            û = 0xAB,
            ü = 0xAC,
            ª = 0xAF,

            A_BUTTON = 0xB0,
            B_BUTTON = 0xB1,
            C_BUTTON = 0xB2,
            L_BUTTON = 0xB3,
            R_BUTTON = 0xB4,
            Z_BUTTON = 0xB5,
            C_UP = 0xB6,
            C_DOWN = 0xB7,
            C_LEFT = 0xB8,
            C_RIGHT = 0xB9,
            TRIANGLE = 0xBA,
            CONTROL_STICK = 0xBB,
            D_PAD = 0xBC
        }

        public enum BoxType
        {
            Black,
            Wooden,
            Blue,
            Ocarina,
            None_White,
            None_Black,
            Black2,
            None,
            Blue2,
            Red,
            None2,
            Credits,
            None3,
            Bombers_Notebook,
            None4,
            Red2
        }

        public static readonly Dictionary<MsgControlCode, string> ControlCharPresets = new Dictionary<MsgControlCode, string>()
        {
            {MsgControlCode.PLAYER,                              "Link"},
            {MsgControlCode.SWAMP_CRUISE_HITS,                   "20" },
            {MsgControlCode.STRAY_FAIRY_SCORE,                   "20th" },
            {MsgControlCode.GOLD_SKULLTULAS,                     "20th" },
            {MsgControlCode.POSTMAN_RESULTS,                     "00\"00" },
            {MsgControlCode.MOON_CRASH_TIME,                     "00\"00" },
            {MsgControlCode.DEKU_RESULTS,                        "00\"00" },
            {MsgControlCode.TIMER,                               "00\"00" },
            {MsgControlCode.TIMER2,                              "00\"00" },
            {MsgControlCode.TIMER3,                              "00\"00" },
            {MsgControlCode.TIMER4,                              "00\"00" },
            {MsgControlCode.SHOOTING_GALLERY_RESULT,             "9999" },
            {MsgControlCode.BANK_PROMPT,                         "0 0 0  Rupee(s)" },
            {MsgControlCode.RUPEES_ENTERED,                      "500 Rupees" },
            {MsgControlCode.RUPEES_IN_BANK,                      "5000 Rupees" },
            {MsgControlCode.TIME_REMAINING,                      "72:00" },
            {MsgControlCode.BET_RUPEES,                          "0 0  Rupees" },
            {MsgControlCode.PROMPT_BOMBER_CODE,                  "0 0 0 0 0" },
            {MsgControlCode.SOARING_DESTINATION,                 "Great Bay Coast" },
            {MsgControlCode.UNK_D3,                              "----" },
            {MsgControlCode.PROMPT_LOTTERY_NUMBER,               "1 1 1" },
            {MsgControlCode.OCEANSIDE_HOUSE_ORDER,               "123456" },
            {MsgControlCode.WOODFALL_FAIRIES_REMAIN,             "15" },
            {MsgControlCode.SNOWHEAD_FAIRIES_REMAIN,             "15" },
            {MsgControlCode.BAY_FAIRIES_REMAIN,                  "15" },
            {MsgControlCode.IKANA_FAIRIES_REMAIN,                "15" },
            {MsgControlCode.SWAMP_CRUISE_RESULT,                 "45" },
            {MsgControlCode.WINNING_LOTTERY_NUM,                 "000" },
            {MsgControlCode.PLAYER_LOTTERY_NUM,                  "000" },
            {MsgControlCode.ITEM_VALUE,                          "500 Rupees" },
            {MsgControlCode.BOMBER_CODE,                         "123456" },
            {MsgControlCode.OCEANSIDE_HOUSE_ORDER_1,             "YELLOW" },
            {MsgControlCode.OCEANSIDE_HOUSE_ORDER_2,             "YELLOW" },
            {MsgControlCode.OCEANSIDE_HOUSE_ORDER_3,             "YELLOW" },
            {MsgControlCode.OCEANSIDE_HOUSE_ORDER_4,             "YELLOW" },
            {MsgControlCode.OCEANSIDE_HOUSE_ORDER_5,             "YELLOW" },
            {MsgControlCode.OCEANSIDE_HOUSE_ORDER_6,             "YELLOW" },
            {MsgControlCode.MOON_CRASH_HOURS_REMAIN,             "72 hours" },
            {MsgControlCode.UNTIL_MORNING,                       "23:59" },
            {MsgControlCode.TOTAL_IN_BANK,                       "5000" },
            {MsgControlCode.TOWN_SHOOTING_HIGHSCORE,             "50" },
            {MsgControlCode.EPONA_ARCHERY_HIGHSCORE,             "99'99\"99" },
            {MsgControlCode.DEKU_HIGHSCORE_DAY1,                 "99'99\"99" },
            {MsgControlCode.DEKU_HIGHSCORE_DAY2,                 "99'99\"99" },
            {MsgControlCode.DEKU_HIGHSCORE_DAY3,                 "99'99\"99" },
            {MsgControlCode.UNK_F4,                              ":0\"00\'" },
            {MsgControlCode.UNK_F3,                              "0\"10\'" },
            {MsgControlCode.UNK_F2,                              "0" },
            {MsgControlCode.UNK_F1,                              "0" },
            {MsgControlCode.FISH_WEIGHT,                         "0" },
        };


        public static readonly List<List<RGB>> CharColors = new List<List<RGB>>()
        {
            new List<RGB>() { new RGB(255,  255,  255),  new RGB(255, 255, 255),  new RGB(0,   0,   0),    new RGB(0,   0,   0)      },
            new List<RGB>() { new RGB(255,  60,   60),   new RGB(255, 120, 0),    new RGB(255, 60, 60),    new RGB(255, 60, 60)      },
            new List<RGB>() { new RGB(70,   255,  80),   new RGB(70,  255, 80),   new RGB(70,  255, 80),   new RGB(124, 179, 255)    },
            new List<RGB>() { new RGB(80,   110,  255),  new RGB(80,  90,  255),  new RGB(80,  110, 255),  new RGB(80,  110, 255)    },
            new List<RGB>() { new RGB(255,  255,  30),   new RGB(255, 255, 50),   new RGB(255, 255, 30),   new RGB(255, 255, 30)     },
            new List<RGB>() { new RGB(74,   138,  234),  new RGB(74,  138, 234),  new RGB(74,  138, 234),  new RGB(74,  138, 234)    },       //??
            new List<RGB>() { new RGB(255,  192,  203),  new RGB(255, 192, 203),  new RGB(255, 192, 203),  new RGB(255, 192, 203)    },       //??
            new List<RGB>() { new RGB(192,  192,  192),  new RGB(192, 192, 192),  new RGB(192, 192, 192),  new RGB(192, 192, 192)    },       //??
            new List<RGB>() { new RGB(255,  165,  0),    new RGB(255, 165, 0),    new RGB(255, 165, 0),    new RGB(255, 165, 0)      },       //??
        };

        public static Dictionary<MsgControlCode, List<RGB>> SpecificTagTextColor = new Dictionary<MsgControlCode, List<RGB>>()
        {
            { MsgControlCode.A_BUTTON,      new List<RGB>() { new RGB(0x41, 0x69, 0xE1), new RGB(0x41, 0x69, 0xE1), new RGB(0x41, 0x69, 0xE1), new RGB(0x41, 0x69, 0xE1) } },
            { MsgControlCode.B_BUTTON,      new List<RGB>() { new RGB(0x32, 0xCD, 0x32), new RGB(0x32, 0xCD, 0x32), new RGB(0x32, 0xCD, 0x32), new RGB(0x32, 0xCD, 0x32) } },
            { MsgControlCode.C_BUTTON,      new List<RGB>() { new RGB(0xFF, 0xFF, 0x00), new RGB(0xFF, 0xFF, 0x00), new RGB(0xFF, 0xFF, 0x00), new RGB(0xFF, 0xFF, 0x00) } },
            { MsgControlCode.R_BUTTON,      new List<RGB>() { new RGB(0xFF, 0xFF, 0xFF), new RGB(0xFF, 0xFF, 0xFF), new RGB(0x00, 0x00, 0x00), new RGB(0x00, 0x00, 0x00) } },
            { MsgControlCode.L_BUTTON,      new List<RGB>() { new RGB(0xFF, 0xFF, 0xFF), new RGB(0xFF, 0xFF, 0xFF), new RGB(0x00, 0x00, 0x00), new RGB(0x00, 0x00, 0x00) } },
            { MsgControlCode.Z_BUTTON,      new List<RGB>() { new RGB(0xFF, 0xFF, 0xFF), new RGB(0xFF, 0xFF, 0xFF), new RGB(0x00, 0x00, 0x00), new RGB(0x00, 0x00, 0x00) } },
            { MsgControlCode.C_UP,          new List<RGB>() { new RGB(0xFF, 0xFF, 0x00), new RGB(0xFF, 0xFF, 0x00), new RGB(0xFF, 0xFF, 0x00), new RGB(0xFF, 0xFF, 0x00) } },
            { MsgControlCode.C_DOWN,        new List<RGB>() { new RGB(0xFF, 0xFF, 0x00), new RGB(0xFF, 0xFF, 0x00), new RGB(0xFF, 0xFF, 0x00), new RGB(0xFF, 0xFF, 0x00) } },
            { MsgControlCode.C_LEFT,        new List<RGB>() { new RGB(0xFF, 0xFF, 0x00), new RGB(0xFF, 0xFF, 0x00), new RGB(0xFF, 0xFF, 0x00), new RGB(0xFF, 0xFF, 0x00) } },
            { MsgControlCode.C_RIGHT,       new List<RGB>() { new RGB(0xFF, 0xFF, 0x00), new RGB(0xFF, 0xFF, 0x00), new RGB(0xFF, 0xFF, 0x00), new RGB(0xFF, 0xFF, 0x00) } },
            { MsgControlCode.TRIANGLE,      new List<RGB>() { new RGB(0x32, 0xCD, 0x32), new RGB(0x32, 0xCD, 0x32), new RGB(0x32, 0xCD, 0x32), new RGB(0x32, 0xCD, 0x32) } },
            { MsgControlCode.CONTROL_STICK, new List<RGB>() { new RGB(0xFF, 0xFF, 0xFF), new RGB(0xFF, 0xFF, 0xFF), new RGB(0x00, 0x00, 0x00), new RGB(0x00, 0x00, 0x00) } },
            { MsgControlCode.D_PAD,         new List<RGB>() { new RGB(0xFF, 0xFF, 0xFF), new RGB(0xFF, 0xFF, 0xFF), new RGB(0x00, 0x00, 0x00), new RGB(0x00, 0x00, 0x00) } },
        };



        public static Dictionary<BoxType, int> CharColorIndexes = new Dictionary<BoxType, int>()
        {
            {BoxType.Black,                 0 },
            {BoxType.Wooden,                1 },
            {BoxType.Blue,                  0 },
            {BoxType.Ocarina,               0 },
            {BoxType.None_White,            0 },
            {BoxType.None_Black,            2 },
            {BoxType.Black2,                0 },
            {BoxType.None,                  0 },
            {BoxType.Blue2,                 0 },
            {BoxType.Red,                   0 },
            {BoxType.None2,                 0 },
            {BoxType.Credits,               0 },
            {BoxType.None3,                 0 },
            {BoxType.Bombers_Notebook,      2 },
            {BoxType.None4,                 0 },
            {BoxType.Red2,                  0 },

        };


        public static int XPOS_DEFAULT = 32;
        public static int LINEBREAK_SIZE = 12;
        public static int YPOS_DEFAULT = 8;
        public static int CHOICE_OFFSET = 0x20;
        public static float SCALE_DEFAULT = 0.75f;

        public static readonly float[] FontWidths =
        {
            /* */ 8.0f,
            /* !*/ 8.0f,
            /* "*/ 6.0f,
            /* #*/ 9.0f,
            /* $*/ 9.0f,
            /* %*/ 14.0f,
            /* &*/ 12.0f,
            /* '*/ 3.0f,
            /* (*/ 7.0f,
            /* )*/ 7.0f,
            /* **/ 7.0f,
            /* +*/ 9.0f,
            /* ,*/ 4.0f,
            /* -*/ 6.0f,
            /* .*/ 4.0f,
            /* /*/ 9.0f,
            /* 0*/ 10.0f,
            /* 1*/ 5.0f,
            /* 2*/ 9.0f,
            /* 3*/ 9.0f,
            /* 4*/ 10.0f,
            /* 5*/ 9.0f,
            /* 6*/ 9.0f,
            /* 7*/ 9.0f,
            /* 8*/ 9.0f,
            /* 9*/ 9.0f,
            /* :*/ 6.0f,
            /* ;*/ 6.0f,
            /* <*/ 9.0f,
            /* =*/ 11.0f,
            /* >*/ 9.0f,
            /* ?*/ 11.0f,
            /* @*/ 13.0f,
            /* A*/ 12.0f,
            /* B*/ 9.0f,
            /* C*/ 11.0f,
            /* D*/ 11.0f,
            /* E*/ 8.0f,
            /* F*/ 8.0f,
            /* G*/ 12.0f,
            /* H*/ 10.0f,
            /* I*/ 4.0f,
            /* J*/ 8.0f,
            /* K*/ 10.0f,
            /* L*/ 8.0f,
            /* M*/ 13.0f,
            /* N*/ 11.0f,
            /* O*/ 13.0f,
            /* P*/ 9.0f,
            /* Q*/ 13.0f,
            /* R*/ 10.0f,
            /* S*/ 10.0f,
            /* T*/ 9.0f,
            /* U*/ 10.0f,
            /* V*/ 11.0f,
            /* W*/ 15.0f,
            /* X*/ 11.0f,
            /* Y*/ 10.0f,
            /* Z*/ 10.0f,
            /* [*/ 7.0f,
            /* ¥*/ 10.0f,
            /* ]*/ 7.0f,
            /* ^*/ 10.0f,
            /* _*/ 9.0f,
            /* `*/ 5.0f,
            /* a*/ 8.0f,
            /* b*/ 9.0f,
            /* c*/ 8.0f,
            /* d*/ 9.0f,
            /* e*/ 9.0f,
            /* f*/ 6.0f,
            /* g*/ 9.0f,
            /* h*/ 8.0f,
            /* i*/ 4.0f,
            /* j*/ 6.0f,
            /* k*/ 8.0f,
            /* l*/ 4.0f,
            /* m*/ 12.0f,
            /* n*/ 9.0f,
            /* o*/ 9.0f,
            /* p*/ 9.0f,
            /* q*/ 9.0f,
            /* r*/ 7.0f,
            /* s*/ 8.0f,
            /* t*/ 7.0f,
            /* u*/ 8.0f,
            /* v*/ 9.0f,
            /* w*/ 12.0f,
            /* x*/ 8.0f,
            /* y*/ 9.0f,
            /* z*/ 8.0f,
            /* {*/ 7.0f,
            /* |*/ 5.0f,
            /* }*/ 7.0f,
            /* ~*/ 10.0f,
            /* ‾*/ 10.0f,

            /* À*/ 12.0f,
            /* Á*/ 12.0f,
            /* Â*/ 12.0f,
            /* Ä*/ 12.0f,
            /* Ç*/ 11.0f,
            /* È*/ 8.0f,
            /* É*/ 8.0f,
            /* Ê*/ 8.0f,
            /* Ë*/ 8.0f,
            /* Ï*/ 6.0f,
            /* Ì*/ 6.0f,
            /* Î*/ 6.0f,
            /* Ï*/ 6.0f,
            /* Ñ*/ 12.0f,
            /* Ò*/ 13.0f,
            /* Ó*/ 13.0f,
            /* Ô*/ 13.0f,
            /* Ö*/ 13.0f,
            /* Ù*/ 10.0f,
            /* Ú*/ 10.0f,
            /* Û*/ 10.0f,
            /* Ü*/ 10.0f,
            /* ß*/ 9.0f,
            /* à*/ 8.0f,
            /* á*/ 8.0f,
            /* â*/ 8.0f,
            /* ä*/ 8.0f,
            /* ç*/ 8.0f,
            /* è*/ 9.0f,
            /* é*/ 9.0f,
            /* ê*/ 9.0f,
            /* ë*/ 9.0f,
            /* ì*/ 6.0f,
            /* í*/ 6.0f,
            /* î*/ 5.0f,
            /* ï*/ 5.0f,
            /* ñ*/ 10.0f,
            /* ò*/ 9.0f,
            /* ó*/ 9.0f,
            /* ô*/ 9.0f,
            /* ö*/ 9.0f,
            /* ù*/ 9.0f,
            /* ú*/ 9.0f,
            /* û*/ 9.0f,
            /* ü*/ 9.0f,
            /* ¡*/ 6.0f,
            /* ¿*/ 11.0f,
            /* ª*/ 8.0f,

            /* [A] */ 14.0f,
            /* [B] */ 14.0f,
            /* [C] */ 14.0f,
            /* [L] */ 14.0f,
            /* [R] */ 14.0f,
            /* [Z] */ 14.0f,
            /* [C-Up] */ 14.0f,
            /* [C-Down] */ 14.0f,
            /* [C-Left] */ 14.0f,
            /* [C-Right] */ 14.0f,
            /* ▼*/ 14.0f,
            /* [Analog-Stick] */ 14.0f,
            /* [D-Pad] */ 14.0f,
            /* ?*/ 14.0f,
            /* ?*/ 14.0f,
            /* ?*/ 14.0f,
            /* ?*/ 14.0f,
        };
    }
}
